FROM node:18

WORKDIR /app

# Install dependencies for better-sqlite3
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

# Clean install dependencies
RUN npm install


COPY . .

EXPOSE 3001

CMD ["npm", "run", "server"]
